# NB comments only work as their own line.
# Do not make comments mid-line
# Remember #keyd -c /etc/keyd/keyd.conf

[ids]
*

# layered context-dependent ctrl key for emacs and vi
[main]
# replace pgup key for ThinkPad X 2-in-1
pageup = rightmeta
# replace screenshot key with meta
# sysrq = rightmeta

capslock = overload(capslock, esc)

# when ctrl is held, the letter presses will be substituted for..
[capslock:C]
# vi-bindings; left column is qwerty
# colemakH = H(qwerty)
h = left
# y = down  (J in colemak)
y = down
# n = up    (K in colemak)
n = up
# u = right (L in colemak)
u = right
# o = tab   (Y in colemak)
o = tab
# leftbrace = escape (\^\[  \(escape in \^ and M\- notation))
leftbrace = escape

# emacs-bindings left column is qwerty
# j = down   (n in colemak)
j = down
# r = up     (p in colemak)
r = up
# a = home   (a)
a = home
# k = end    (e in colemak)
k = end
# g = delete (d in colemak)
g = delete

# other bindings
# quote = enter

