# NB comments only work as their own line.
# Do not make comments mid-line
# Remember #keyd -c /etc/keyd/keyd.conf

[ids]
*

# layered context-dependent ctrl key for emacs and vi
[main]
# replace pgup key for ThinkPad X 2-in-1
pageup = rightmeta
# replace screenshot key with meta (ThinkPad Yoga)
# sysrq = rightmeta

capslock = overload(capslock, esc)
# Right Control: Control when held, Escape when tapped
rightcontrol = overload(control, esc)

# when ctrl is held, the letter presses will be substituted for..
[capslock:C]
### VIM LIKE BINDINGS ###
# vi-bindings; left column is qwerty
# colemakH = H(qwerty)
h = left
# y = down  (J in colemak)
y = down
# n = up    (K in colemak)
n = up
# u = right (L in colemak)
u = right
# leftbrace = escape (\^\[  \(escape in \^ and M\- notation))
leftbrace = escape
# l = tab (i in colemak) # for POSIX General terminal input ala C-H==BackSpace
l = tab
# o = tab   (Y in colemak) # disabled due to bad habits as C-[Y]es when C-I is POSIX for Tab which are semantically different
# o = tab

# emacs-bindings left column is qwerty
# j = down   (n in colemak)
j = down
# r = up     (p in colemak)
r = up
# p = up (p in qwerty, r in colemak)
p = up
# a = home   (a)
a = home
# k = end    (e in colemak)
k = end
# g = delete (d in colemak)
g = delete

# other bindings
# quote = enter
[control:C]
h = backspace
# b = left # emacs
# b = left
# e = right # C-f emacs binding
# e = right
# g = delete # C-d emacs and posix
# g = delete
# l = tab
# l = tab
# o = paste
# o = paste
