# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
# From thread: https://www.reddit.com/r/hyprland/comments/1hfjw1h/wanna_move_cursor_with_numpad_aka_mouse_keymouse/
# #(src cGPT)
binde = , KP_HOME, exec, ydotool mousemove -- -18 -18 && sleep 0.1   # Left-Up
binde = , KP_PRIOR, exec, ydotool mousemove -- 18 -18 && sleep 0.1   # Right-Up
binde = , KP_END, exec, ydotool mousemove -- -18 18 && sleep 0.1     # Left-Down
binde = , KP_NEXT, exec, ydotool mousemove -- 18 18 && sleep 0.1     # Right-Down
binde = , KP_LEFT, exec, ydotool mousemove -- -18 0 && sleep 0.1  # Left
binde = , KP_RIGHT, exec, ydotool mousemove -- 18 0 && sleep 0.1  # Right
binde = , KP_UP, exec, ydotool mousemove -- 0 -18 && sleep 0.1  # Up
binde = , KP_DOWN, exec, ydotool mousemove -- 0 18 && sleep 0.1  # Down
# binde = SHIFT, KP_LEFT, exec, ydotool mousemove -- -9 0 && sleep 0.1  # Left
# binde = SHIFT, KP_RIGHT, exec, ydotool mousemove -- 9 0 && sleep 0.1  # Right
# binde = SHIFT, KP_UP, exec, ydotool mousemove -- 0 -9 && sleep 0.1  # Up
# binde = SHIFT, KP_DOWN, exec, ydotool mousemove -- 0 9 && sleep 0.1  # Down
bind = , KP_BEGIN, exec, ydotool click C0
bind = , KP_DIVIDE, exec, ydotool click 0x40
bind = , KP_MULTIPLY, exec, ydotool click 0x42 0x82
bind = , KP_SUBTRACT, exec, ydotool click 0x41 0x81
bind = , KP_INSERT, exec, sh -c 'if [ "$(cat /tmp/mouse_state)" = "40" ]; then echo "80" > /tmp/mouse_state && ydotool click 0x80; else echo "40" > /tmp/mouse_state && ydotool click 0x40; fi'
bind = , KP_Enter, exec, sudo pkill ydotoold
bind = , KP_Add, exec, sudo ydotoold --socket-perm=0666 --socket-path=/run/user/1000/.ydotool_socket
