[ids]
047d:805b:*

[main]
rightalt=layer(meta)
leftalt=layer(meta)
leftmeta=layer(alt)
rightmeta=layer(alt)

[capslock:C]
# vi-bindings; left column is qwerty
# colemakH = H(qwerty)
h = left
y = down
n = up
u = right
# leftbrace = escape (\^\[  \(escape in \^ and M\- notation))
leftbrace = escape
# l = tab (i in colemak) # for POSIX General terminal input ala C-H==BackSpace
l = tab

# emacs-bindings left column is qwerty
j = down
r = up
p = up
a = home
k = end
# g = delete (d in colemak)
g = delete

# [control:C]
# h = backspace
