# NB comments only work as their own line.
# Do not make comments mid-line
# Remember `keyd -c /etc/keyd/keyd.conf`

[ids]
*

# layered context-dependent ctrl key for emacs and vi
[main]
rightalt=layer(meta)
leftalt=layer(meta)
leftmeta=layer(alt)
rightmeta=layer(alt)
# replace screenshot key with meta (ThinkPad Yoga)
# pageup = rightmeta
# sysrq = rightmeta

backslash = overload(capslock, esc)
capslock = overload(capslock, esc)
# Right Control: Control when held, Escape when tapped
rightcontrol = overload(control, esc)

# when ctrl is held, the letter presses will be substituted for..
[capslock:C]
### VIM LIKE BINDINGS ###
# vi-bindings; left column is qwerty
h = left
y = down
n = up
u = right
# leftbrace = escape (\^\[  \(escape in \^ and M\- notation))
leftbrace = escape
# l = tab (i in colemak) # for POSIX General terminal input ala C-H==BackSpace
l = tab

# emacs-bindings left column is qwerty
j = down
r = up
p = up
# a = home   (a)
a = home
# k = end    (e in colemak)
k = end
# g = delete (d in colemak)
g = delete

# other bindings
# quote = enter
# [control:C]
# h = backspace
# b = left # emacs
# b = left
# e = right # C-f emacs binding
# e = right
# g = delete # C-d emacs and posix
# g = delete
# l = tab
# l = tab
# o = paste
# o = paste
